name: CI Workflow ARM

on:
    workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        config: [debug, release]
        include:
          - arch: aarch64
            distro: ubuntu20.04

    runs-on: ubuntu-20.04

    name: Build on ${{ matrix.distro }} ${{ matrix.arch }} ${{ matrix.config }}

    steps:
      - uses: actions/checkout@v2

      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          # setup: |
          #   mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          # dockerRunArgs: |
          #   --volume "${PWD}/artifacts:/artifacts"
          
          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            CC: gcc
            CXX: g++
            PLATFORM: ${{ matrix.arch }}
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true

          install: |
            apt-get update -q -y
            apt-get install -q -y --no-install-recommends cmake make build-essential gdb git apt-utils curl uuid-dev

          run: |
            pwd
            ls -al "${PWD}"
            echo "Build"
            make -f Bootstrap.mak linux PLATFORM=${{ matrix.arch }} CONFIG=${{ matrix.config }}
            echo "Test"
            bin/${{ matrix.config }}/premake5 test --test-all
            echo "Docs check"
            bin/${{ matrix.config }}/premake5 docs-check

      - name: Upload Artifacts
        if: matrix.config == 'release'
        uses: actions/upload-artifact@v2
        with:
          name: premake-linux-${{ matrix.arch }}
          path: bin/${{ matrix.config }}/
